version: '3'

services:
    openstreetmap:
        build: 
            context: .
            args:
                BUILD_THREADS: 4
                BUILD_MEMORY: 8GB
                OSM2PGSQL_CACHE: 2000
                RUNTIME_THREADS: 2
                RUNTIME_MEMORY: 8GB
                PGSQL_VERSION: 9.3
                PBF_URL: https://download.geofabrik.de/europe/france-latest.osm.pbf
                REPLICATION_URL: http://download.geofabrik.de/europe/france-updates
        restart: always
        ports:
            - "80:80"
        #logging:
        #    driver: gcplogs
        #    options:
        #        mode: non-blocking